#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault_library=static \
    -Denable-docs=false \
    -Denable-xkbregistry=false \
    -Denable-x11=false \
    -Denable-wayland=true \
    . output

ninja -C output
ninja -C output install
