#!/bin/sh -e

export LDFLAGS="$LDFLAGS  --static"

./configure \
	--without-brotli \
	--without-bzip2 \
	--without-lzip \
	--without-openmp \
	--without-libevent \
  --without-zstd

make 

mkdir -p \
	"$1/usr/share/man/man1" \
	"$1/usr/bin/"

cp links "$1/usr/bin/"
cp links.1 "$1/usr/share/man/man1" 
