#!/bin/sh -e

export LDFLAGS="$LDFLAGS  --static"

# disable ipv6 if sdhcp is used instead of dhcpcd
if kiss l sdhcp; then

./configure \
	--without-brotli \
	--without-bzip2 \
	--without-lzip \
	--without-openmp \
	--without-libevent \
  --without-zstd \
  --without-ipv6

else

./configure \
	--without-brotli \
	--without-bzip2 \
	--without-lzip \
	--without-openmp \
	--without-libevent \
  --without-zstd

fi

make 

mkdir -p \
	"$1/usr/share/man/man1" \
	"$1/usr/bin/"

cp links "$1/usr/bin/"
cp links.1 "$1/usr/share/man/man1" 
