#!/bin/sh -e

# add amd to the list of drm drivers.
sed 's/intel/& amd/' config.mk > _
mv -f _ config.mk

mk() {
    make \
        PREFIX=/usr \
        ENABLE_DEBUG=0 \
        ENABLE_SHARED=0 \
        "$@"
}

mk
mk install
