#!/bin/sh -e

mkdir -m 755 \
    "$1/boot" \
    "$1/dev" \
    "$1/etc" \
    "$1/home" \
    "$1/mnt" \
    "$1/run" \
    "$1/usr" \
    "$1/usr/bin" \
    "$1/usr/lib" \
    "$1/usr/sbin" \
    "$1/usr/share" \
    "$1/usr/share/man"

mkdir -m 555 \
    "$1/proc" \
    "$1/sys"

mkdir -m 0750 "$1/root"

mkdir -m 1777 "$1/tmp" \

ln -sf usr/bin "$1/bin"
ln -sf usr/bin "$1/sbin"
ln -sf bin     "$1/usr/sbin"
ln -sf usr/lib "$1/lib"

ln -sf ../run            "$1/var/run"
ln -sf /proc/self/mounts "$1/etc/mtab"

cp -f ./* "$1/etc"

chmod 600 "$1/etc/shadow"
