#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"

# Disable HTML documentation.
sed 's/html man/man/' doc/Makefile.in > _
mv -f _ doc/Makefile.in

./configure \
    ac_cv_lib_ncurses_initscr=no \
    ac_cv_lib_curses_initscr=no \
    --prefix=/usr \
    --disable-shared \
    --disable-gtktest

make
make install
