#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --with-openssl \
    --without-pic \
    --with-ca-fallback \
    --without-librtmp \
    --without-icu \
    --without-libpsl \
    --without-libidn \
    --without-libidn2 \
    --without-zstd \
    --without-zlib \
    --disable-shared \
    --without-brotli

make LDFLAGS=--static
make install
