#!/bin/sh -e

# curl doesnt have this option, and when trying to start a video, curl will
# error out. this fixes the issue
sed 's/--compressed/#--compressed/' ytfzf > _
mv -f _ ytfzf

sed 's/doc:/install:/' Makefile > _
mv -f _ Makefile

make PREFIX=/usr DESTDIR="$1" install

# Makefile doesnt install manpage and doc, so we install it ourselves
mkdir -p \
    "$1/etc" \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man5" \
    "$1/usr/share/doc/ytfzf"

cp -f docs/man/ytfzf.1 "$1/usr/share/man/man1"
cp -f docs/man/ytfzf.5 "$1/usr/share/man/man5"
cp -f docs/conf.sh "$1/usr/share/doc/ytfzf"
