#!/bin/sh -e

cat <<EOF

NOTE: A menu system has to be installed. Possible choices:

- fzf
  - or fzy with our patch
- dmenu (default ext. menu)
- bemenu
- rofi

To use an external menu, see

  man 5 ytfzf

  And configure conf.sh file accordingly.


Optional dependencies like thumbnail viewers can be found here:

https://github.com/pystardust/ytfzf#optional-dependencies


NOTE: if mpv fails to play the video, it needs to be
rebuilt. 

EOF
