#!/bin/sh -e

cat <<EOF

NOTE: A menu system has to be installed. Possible choices:

- fzf
- dmenu (default ext. menu)
- bemenu
- rofi

To use an external menu, the variable YTFZF_EXTMENU has
to be set. Example:

export YTFZF_EXTMENU="bemenu -l 15"

Optional: ueberzug can be installed with 'pip'
to get thumbnails support.


NOTE: if mpv fails to play the video, it needs to be
rebuilt. 

A sample configuration file can be found in /usr/share/doc/ytfzf.
Copy this to $HOME/.config/ytfzf if you wish to alter it per user.

EOF
