#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-tests \
    --disable-shared

make
make install

# when compiling linux with static libressl, it kept complaining about missing
# libcrypto.so.1.1. We dont have that, seeing as we compile it statically.
# creating this symlink however, seemed to fix it
ln -s "$1/usr/lib/libcrypto.a" "$1/usr/lib/libcrypto.so.1.1"

install -Dm 755 update-certdata.sh "$1/etc/ssl"
