#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-tests \
    --disable-shared

make
make install

install -Dm 755 update-certdata.sh "$1/etc/ssl"

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libressl.license"
