#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

mkdir -p \
    "$1/usr/bin/" \
    "$1/usr/lib/dhcpcd"

# build udev.a instead of udev.so
sed -i 's/-shared/-static/' src/dev/Makefile
sed -i 's/.So/.a/g' src/dev/Makefile
sed -i 's/.so/.a/g' src/dev/Makefile

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --rundir=/run \
    --libexecdir=/usr/lib/dhcpcd

make
make BINMODE=755 install

# Install runit service.
mkdir -p "$1/etc/sv/dhcpcd"
cp -f dhcpcd.run "$1/etc/sv/dhcpcd/run"
ln -sf /run/runit/supervise.dhcpcd "$1/etc/sv/dhcpcd/supervise"
