#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -fPIC -I$1/usr/include"
export CFLAGS="$CFLAGS -I$1/usr/include/libevdev-1.0"
export PKG_CONFIG_PATH="$1/usr/lib/pkgconfig"
export LDFLAGS="-L$1/usr/lib --static"

patch -p1 < evdev-wrap.patch

for pkg in mtdev evdev; do (
    cd "$pkg"

    ./configure \
        --prefix=/usr \
        --disable-shared \
        --disable-gcov

    make
    make install
) done

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"


sed 's/shared_library/library/' meson.build > _
mv -f _ meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    -Ddefault_library=static \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . output

ninja -C output
ninja -C output install
