#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

mk() {
    make \
        PREFIX=/usr \
        ENABLE_DEBUG=0 \
        ENABLE_SHARED=0 \
        ENABLE_XWAYLAND=0 \
        "$@"
}

mk
mk DESTDIR="$1" install
