#!/bin/sh -e

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-pc-files \
    --disable-rpath-hack \
    --with-pkg-config-libdir=/usr/lib/pkgconfig \
    --enable-widec \
    --without-ada \
    --without-tests \
    --without-debug \
    --without-cxx-binding \

make LDFLAGS="$LDFLAGS -static"
make install

# Fix pkgconfig file.
ln -s ncursesw.pc "$1/usr/lib/pkgconfig/ncurses.pc"

# fix some packages complaining about missing curses libs
ln -s libncursesw.a "$1/usr/lib/libncurses.a"

# Force ncurses to link against wide-character ncurses library.
for lib in ncurses form panel menu; do
    ln -sf "lib${lib}w.a" "$1/usr/lib/lib${lib}.a"
done
