#!/bin/sh -e

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-pc-files \
    --disable-rpath-hack \
    --with-pkg-config-libdir=/usr/lib/pkgconfig \
    --enable-widec \
    --without-ada \
    --without-tests \
    --without-debug \
    --without-cxx-binding \
    --without-shared

make LDFLAGS="$LDFLAGS -static"
make install

# Fix pkgconfig file.
ln -s ncursesw.pc "$1/usr/lib/pkgconfig/ncurses.pc"
