#!/bin/sh -e

sed -i '/<libgen.h>/a #include <sys/sysmacros.h>' smdev.c

make LDFLAGS=-static
make PREFIX=/usr DESTDIR="$1" install

ln -sv smdev "$1/usr/bin/mdev"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/smdev.license"
