#!/usr/bin/sh -e

patch -p1 < musl.patch

# should use CC instead of gcc, which may prohibit building with llvm
sed -i 's/gcc/cc/' Makefile

make CFLAGS="-DNCURSESW_INCLUDE_H=\<curses.h\> $CFLAGS --static" 

mkdir -p \
    "$1/usr/bin/" \
    "$1/usr/share/man/man1"

# instead of altering the Makefile, we just copy the wanted files
cp mtm "$1/usr/bin" 
cp mtm.1 "$1/usr/share/man/man1"
