#!/bin/sh -e

export CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1"

sed -i 's/ -ltinfo//g' configure

./configure \
    --prefix=/usr \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5 \
    --disable-shared

make LDFLAGS=--static
make  install
