#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-shared

make LDFLAGS="$LDFLAGS --static"
make install

ln -s pkgconf "$1/usr/bin/pkg-config"

# Remove documentation (README, etc).
rm -rf "$1/usr/share/doc"
