#!/bin/sh -e

# Setup docutils to generate manual pages.
{
   cd docutils

     python3 setup.py build
     python3 setup.py install \
         --root="$PWD/../dist"

     cd ../dist/usr/lib/python*/site-packages

     PYTHONPATH=$PWD:$(python -c "import sys;print(':'.join(sys.path))")

     cd -; cd ..
     export PATH="$PWD"/dist/usr/bin:"$PATH"
     export PYTHONPATH
 
}

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static"

meson \
    --prefix=/usr \
    -Dalsa=enabled \
    -Degl=disabled \
    -Dgl=disabled \
    -Dx11=disabled \
    -Ddrm=disabled \
    -Dwayland=enabled \
    -Dmanpage-build=enabled \
    . build

ninja -C build
ninja -C build install

# we probably dont need these
rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/icons"
