#!/bin/sh -e

export DESTDIR=$1
export LDFLAGS="$LDFLAGS -static"

meson \
    --prefix=/usr \
    -Dalsa=enabled \
    -Degl=disabled \
    -Dgl=disabled \
    -Dx11=disabled \
    -Ddrm=disabled \
    -Dwayland=enabled \
    . build

ninja -C build
ninja -C build install

# we probably dont need these
rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/icons"

# use pregenerated manpage instead of making our own
mkdir -p "$1/usr/share/man/man1"
cp mpv.1 "$1/usr/share/man/man1"
