#!/bin/sh -e

# configure first, so meson generates ninja.build
meson \
    --prefix=/usr \
    --buildtype=release \
    --force-fallback-for=tllist \
    -Djpeg=enabled \
    -Dpng=enabled \
    . output

# force static flag, and the use of static libs
sed -i 's/LINK_ARGS = /LINK_ARGS = -static /g' output/build.ninja
sed -i 's/ARGS = /ARGS = -static /g' output/build.ninja
sed -i 's/libffi.so/libffi.a/g' output/build.ninja
sed -i 's/libpng16.so/libpng16.a/g' output/build.ninja
sed -i 's/libpixman-1.so/libpixman-1.a/g' output/build.ninja

ninja -C output
ninja -C output install
