#!/bin/sh -e

# configure first, so meson generates ninja.build
meson \
    --prefix=/usr \
    --buildtype=release \
    --force-fallback-for=tllist \
    -Djpeg=enabled \
    -Dpng=enabled \
    . output

# force static flag, and the use of static libs, because meson doesnt seem to
# respect exported CFLAGS/LDFLAGS 
patch -p1 < static.patch

ninja -C output
ninja -C output install
