#!/bin/sh -e

patch -p1 < wld.patch

export LDFLAGS="$LDFLAGS --static -L/usr/lib  /usr/lib/libfontconfig.a  \
	-lfreetype /usr/lib/libxml2.a /usr/lib/libwld.a /usr/lib/libpixman-1.a \
	-lswc -lexpat -ldrm -llzma"

# Fix terminfo, which made vim give you a white terminal background.
tic -sx st.info

make

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man1"

cp st "$1/usr/bin"
cp st.1 "$1/usr/share/man/man1"
