#!/bin/sh -e

patch -p1 < 0001-libiberty-Implement-pex_unix_exec_child-using-posix_.patch
patch -p1 < 0002-Adjust-style-to-prevent-gcc-warning.patch
patch -p1 < 0003-Remove-support-for-long-double-in-error-formatter.patch
patch -p1 < 0004-bfd-Remove-return-with-expression-in-void-function.patch

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH="$PATH":"$PWD"

./configure \
    --prefix=/usr \
    --with-lib-path=/usr/lib:/usr/local/lib \
    --enable-targets=x86_64-pep \
    --enable-deterministic-archives \
    --disable-gold \
    --enable-lto \
    --enable-ld=default \
    --enable-plugins \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --with-mmap \
    --with-system-zlib

make configure-host
make tooldir=/usr LDFLAGS="$LDFLAGS --static -lz -lfl"
make tooldir=/usr install

ln -sf ld.bfd "$1/usr/bin/ld"
