#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"
./configure \
    --prefix=/usr \
    --disable-shared \
    --disable-tiff \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make install
