#!/bin/sh -e

# if alsa-lib fails and complains about a missing reference to
# _sdn_module_control_empty, uncomment these
#./configure \
    #--prefix=/usr \
    #--without-debug 

#make

./configure \
    --prefix=/usr \
    --without-debug \
    --disable-shared \
    --enable-static

make LDFLAGS="$LDFLAGS --static"
make install
