#!/bin/sh -e

patch -p1 < no-docs.patch

export LDFLAGS="$LDFLAGS -static"

# Enabling/disabling shared/static is ignored by cmake for some reason.
# So instead we force FALSE value on building shared libs.
sed -i 's|option(ENABLE_SHARED "Build shared libraries" TRUE)|option(ENABLE_SHARED "Build shared libraries" FALSE)|' CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \

cmake --build   build
cmake --install build
