#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus \
    --disable-shared \
    --enable-static

make LDFLAGS="$LDFLAGS --static"
make install

cp -f iwd_passphrase "$1/usr/bin"
