#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus \
    --disable-systemd-service \
    --enable-static \
    --disable-shared

make
make DESTDIR="$1" install

# Install runit service.
install -Dm755 eiwd.run         "$1/etc/sv/eiwd/run"
ln -s /run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
