#!/bin/sh -e

sed -i '/<libgen.h>/a #include <sys/sysmacros.h>' smdev.c

make LDFLAGS=-static
make PREFIX=/usr install

# make compatible with current baseinit
ln -sv smdev "$1/usr/bin/mdev"

mkdir -p "$1/etc/rc.d"

# smdev might not work properly without this file.
cp perms.boot "$1/etc/rc.d"
