#!/bin/sh -e

# Uncomment if using valgrind or similar.
# :>nostrip

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib \
    --disable-shared \
# Uncomment if using valgrind or similar.
#   --enable-debug

make
make install

# Install BSD compatibility headers.
cp -f cdefs.h queue.h tree.h \
    "$1/usr/include/sys"

mkdir -p "$1/usr/bin"

# Install getconf.
cc -static getconf.c -o "$1/usr/bin/getconf"
cc -static getent.c  -o "$1/usr/bin/getent"
