#!/bin/sh -e

# disable ipv6, if sdhcp is used
if kiss l sdhcp; then

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-screen=ncursesw \
    --with-ssl \
    --with-zlib \
    --disable-ipv6

else

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-screen=ncursesw \
    --with-ssl \
    --with-zlib \
    --enable-ipv6

fi

make LDFLAGS="$LDFLAGS --static"
make install
