#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static-pie -s"
export CFLAGS="$CFLAGS -fPIE"

patch -p1 < cmake-no-execinfo.patch

# should no longer complain about libs
sed -i 's,curses_version,baudrate,'   \
    Source/Checks/Curses/CheckCurses.c
sed -i 's,defined(HAVE_LIBCRYPTO),0,' \
    Utilities/cmlibarchive/libarchive/archive_hmac.c


if kiss l cmake; then


    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=False \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_BZIP2=True \
        -DBUILD_TESTING=OFF

    cmake --build   build
    cmake --install build

else

    ./configure \
        --prefix=/usr \
        --no-system-curl \
        --system-expat \
        --system-zlib \
        --system-bzip2

    make
    make install

fi

rm -rf \
    "$1/usr/doc" \
    "$1/usr/share/cmake"*/Help \
    "$1/usr/share/bash-completion"
