#!/bin/sh -e

sh autogen.sh

./configure \
    --prefix=/usr \
    --with-threads \
    --with-history \
    --without-python \
    --without-icu \
    --disable-shared

make LDFLAGS="$LDFLAGS --static"
make  install
