#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"
export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Ddocs=disabled \
    -Dexamples=disabled \
    -Ddefault_library=static \
    . build

ninja -C build
ninja -C build install
