#!/bin/sh -e

: > completions/meson.build

export LDFLAGS="$LDFLAGS -static"

# we need to configure first, to generate build.ninja, which we need later
meson \
    --prefix=/usr \
    --buildtype=release \
    . output

# force static lib, and force remove the use of PIC, which is unsupported by
# static building.
sed -i 's/libffi.so/libffi.a/g' output/build.ninja
sed -i 's/-fPIC //g' output/build.ninja

ninja -C output
ninja -C output install
