#!/bin/sh -e

make CC="${CC:-cc} $CFLAGS -static"

mkdir -p "$1/usr/bin"

for bin in bzip2 bzdiff bzgrep bzip2recover bzmore; do
    cp "$bin" "$1/usr/bin/$bin"
    chmod 755 "$bin" "$1/usr/bin/$bin"
done

cp -f libbz2.a        "$1/usr/lib/libbz2.a"
cp -f bzip2.1         "$1/usr/share/man/man1/bzip2.1"
cp -f bzlib.h         "$1/usr/include/bzlib.h"

ln -sf bzip2 "$1/usr/bin/bunzip2"
ln -sf bzip2 "$1/usr/bin/bzcat"
