#!/bin/sh -e

export PKG_CONFIG_PATH="/usr/lib/pkgconf"

./configure \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --prefix=/usr \
    --disable-debug \
    --disable-libxml2 \
    --enable-gpl \
    --enable-libass \
    --enable-libdrm \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libxvid \
    --disable-ffplay \
    --enable-nonfree \
    --enable-openssl \
    --enable-version3 \
    --x86asmexe=nasm \
    --pkg-config-flags="--static" \
    --extra-ldexeflags="-static" \
    --extra-ldflags="-L/usr/lib"

make
make install

rm -rf "$1/usr/share/ffmpeg/examples"
