#!/bin/sh -e

export DESTDIR=$1

meson \
    --prefix=/usr \
    -Dalsa=enabled \
    -Degl=disabled \
    -Dgl=disabled \
    -Dx11=disabled \
    -Ddrm=disabled \
    -Dsdl2=enabled \
    -Dwayland=enabled \
    . build

ninja -C build
ninja -C build install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"

# use pregenerated manpage instead of making our own
mkdir -p "$1/usr/share/man/man1"
cp mpv.1 "$1/usr/share/man/man1"
