#!/bin/sh -e

make \
	PREFIX=/usr \
	ENABLE_DEBUG=0 \
	LDFLAGS="$LDFLAGS --static" \
  PKG_CONFIG="pkg-config --static"

make PREFIX=/usr \
	ENABLE_DEBUG=0 \
	install

cp -f velox.conf.sample "$1/etc/velox.conf"
