#!/bin/sh -e

export CFLAGS="$CFLAGS -DSMALL"

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --mandir=/usr/share/man \
    --enable-ksh \
    --enable-static \
    --disable-curses

make 
make install
